title: "Arjun Arunachalam"
description: "A collection of thoughts, ramblings, opinions."
author: "Arjun Arunachalam"

# --- Update this before publishing ---
url: "https://psi25omega.github.io"
baseurl: ""
github_username: psi25omega
# ---------------------------------------

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

sass:
  sass_dir: assets/css

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
